import streamlit as st

from project_config import load_company_universe

st.set_page_config(page_title="Automated Daily Trading System", layout="wide")

st.title("Automated Daily Trading System")
st.write(
    """
    This application connects SimFin market data with our ETL and prediction workflow.
    Use the Go Live page to select a ticker, fetch fresh data, apply transformations,
    and view trading signals generated by the model interface.
    """
)

st.subheader("Team")
st.write(
    """
    - Add team members in this section before final submission.
    - Each member should be able to explain both Part 1 and Part 2 modules in the live Q&A.
    """
)

st.subheader("System Purpose")
st.write(
    """
    - Retrieve financial data from SimFin through an object-oriented Python wrapper.
    - Reuse the ETL transformation logic developed for Part 1.
    - Generate one-day-ahead movement signals in a browser-based UI.
    - Prepare the app for public deployment on Streamlit Cloud.
    """
)

st.subheader("Configured Company Universe")
try:
    configured_symbols = load_company_universe()
except Exception as exc:
    st.error(f"Unable to load company universe from config.toml: {exc}")
else:
    st.write(configured_symbols)

st.info("Navigate to `Go Live` in the left sidebar to run live predictions.")
