try:
    import tomllib
except ImportError:
    import tomli as tomllib  # type: ignore[no-redef]

import streamlit as st

def main():
    st.set_page_config(page_title="Automated Daily Trading System", layout="wide")

    st.title("Automated Daily Trading System")
    st.write(
        """
        This application connects SimFin market data with our ETL and prediction workflow.
        Use the Go Live page to select a ticker, fetch fresh data, apply transformations,
        and view trading signals generated by the model interface.
        """
    )

    st.subheader("Team")
    st.write(
        """
        - Add team members in this section before final submission.
        - Each member should be able to explain both Part 1 and Part 2 modules in the live Q&A.
        """
    )

    st.subheader("System Purpose")
    st.write(
        """
        - Retrieve financial data from SimFin through an object-oriented Python wrapper.
        - Reuse the ETL transformation logic developed for Part 1.
        - Generate one-day-ahead movement signals in a browser-based UI.
        - Prepare the app for public deployment on Streamlit Cloud.
        """
    )

    st.subheader("Configured Company Universe")
    try:
        with open("src/config.toml", "rb") as f:
            tickers = tomllib.load(f).get("tickers", [])
        st.write(tickers)
    except Exception as exc:
        st.error(f"app.py: Unable to load tickers from src/config.toml: {exc}")

    st.info("Navigate to `Go Live` in the left sidebar to run live predictions.")

if __name__ == "__main__":
    main()