companies = ["AMAZON COM INC", "MICROSOFT CORP", "APPLE INC", "AAON INC", "ALLSTATE CORP"]
tickers = ["AMZN", "MSFT", "AAPL", "AAON", "ALL"]

ETL_DIR = "ETL"
BRONZE_DIR = "ETL/data/bronze"
SILVER_DIR = "ETL/data/silver"
GOLD_DIR = "ETL/data/gold"