try:
    import tomllib
except ImportError:
    import tomli as tomllib  # type: ignore[no-redef]

import streamlit as st

def main():
    st.set_page_config(page_title="Automated Daily Trading System", layout="wide")

    st.title("Automated Daily Trading System")
    st.write(
        """
        This application connects SimFin market data with our ETL and prediction workflow.
        Use the Go Live page to select a ticker, fetch fresh data, apply transformations,
        and view trading signals generated by the model interface.
        """
    )

    st.subheader("System Purpose")
    st.write(
        """
        - Retrieve financial data from SimFin through an object-oriented Python wrapper.
        - Reuse the ETL transformation logic developed for Part 1.
        - Generate one-day-ahead movement signals in a browser-based UI.
        - Prepare the app for public deployment on Streamlit Cloud.
        """
    )

    st.subheader("Pipeline")
    col1, col2, col3, col4, col5 = st.columns(5)

    with col1:
        st.write("Data Ingestion")
        st.write("- Ingest data from SimFin for all companies in the config file.")
    with col2:
        st.write("Data Cleaning")
        st.write("- Clean and narrow the raw market data by selecting only the configured companies, removing unneeded columns, and saving one cleaned parquet file per company for downstream processing.")
    with col3:
        st.write("Feature Engineering")
        st.write("- Transform cleaned share-price data into features suitable for machine learning.")
    with col4:
        st.write("Model Training")
        st.write("- Train a binary classifier and regression model to predict next-day movement using the engineered features.")
    with col5:
        st.write("Backtesting")
        st.write("- Run a simple backtest on the model’s predictions to simulate trading performance.")

    st.subheader("Live App Functionality")
    st.write(
        """
        - Retrieve financial data from SimFin through an object-oriented Python wrapper.
        - Reuse the ETL transformation logic developed for Part 1.
        - Generate movement signals based on classification model.
        - View trading signals and backtest results for selected date range and company.
        """
    )

    st.subheader("Configured Company Universe")
    try:
        with open("src/config.toml", "rb") as f:
            tickers = tomllib.load(f).get("tickers", [])
        st.write(tickers)
    except Exception as exc:
        st.error(f"app.py: Unable to load tickers from src/config.toml: {exc}")

if __name__ == "__main__":
    main()